### ISSUE TITLE
Program not auto starting. (Windows 11)

### ISSUE THREAD

**Issue by lividhen** [Toxblh/WinToLinux#2]
The program does not seem to auto start even when "Start With System" is checked. The entry shows up as WinToLinux.exe in task manager and displays as "Enabled", but never starts.

**Windows 11**
**Version** 22H2
**Experience** Windows Feature Experience Pack 1000.22638.1000.0

Thank you for this software by the way. I have been looking for something exactly like this for years.

**Comment by Toxblh** [comment]
Wow, thanks for the first issue. 
I'll see why it's not working. Maybe it's never doing this...

**Comment by Toxblh** [comment]
So, I investigated the problem..
Main is UAC in Windows will block startup app at launch if the app is req admin rights.
Second one - my app is required admin rights by default even to collect of options, change order and reboot. All of it is req admin rights. 

I already tried put in reg (current in sources)
Also created a shortcut in start-up folder and the same state.

I think better to remove the option from app, because it never be work as I planned. 

source: https://www.codeproject.com/Questions/5254576/How-do-I-run-as-administrator-Csharp-program-in-st

Upd: it's not a final decision, only if all workarounds doesn't work. I'll try it on the week. 
But all else is ugly a bit, and looks like a bit tricky cases instead of a legal way :)

**Comment by lividhen** [comment]
Is it possible to create a task in Windows Task Scheduler as a program? Creating one as a user this seems to work great. 
[Win To Linux.zip](https://github.com/Toxblh/WinToLinux/files/10422330/Win.To.Linux.zip)
(I put WinToLinux.exe in Program Files to try to keep things organized)
There looks to be a wrapper but it doesnt seem to support UWP. You could create an installer or a powershell script to get around this, but im not sure if thats something you want to do.

**Comment by lividhen** [comment]
Awesome! Works great!
